# Load Testing Profiles for Different Scenarios

profiles:
  # Light load for development testing
  development:
    concurrent_users: 2
    spawn_rate: 0.5
    duration: 300  # 5 minutes
    think_time:
      min: 2
      max: 8
  
  # Realistic production-like load
  realistic:
    concurrent_users: 10
    spawn_rate: 1
    duration: 1800  # 30 minutes
    think_time:
      min: 1
      max: 5
    
  # Stress testing
  stress:
    concurrent_users: 50
    spawn_rate: 5
    duration: 600  # 10 minutes
    think_time:
      min: 0.5
      max: 2
  
  # Peak load simulation
  peak:
    concurrent_users: 100
    spawn_rate: 10
    duration: 300  # 5 minutes
    think_time:
      min: 0.1
      max: 1

# User behavior patterns (weighted)
user_journeys:
  browser:
    weight: 40
    description: "Users who browse but don't buy"
    conversion_rate: 0.05
    
  quick_shopper:
    weight: 25
    description: "Users who know what they want"
    conversion_rate: 0.8
    
  comparison_shopper:
    weight: 20
    description: "Users who compare multiple products"
    conversion_rate: 0.4
    
  returning_user:
    weight: 10
    description: "Logged-in users with history"
    conversion_rate: 0.6
    
  cart_abandoner:
    weight: 5
    description: "Users who add items but don't checkout"
    conversion_rate: 0.0

# Error simulation (realistic failure rates)
error_simulation:
  enabled: true
  network_errors: 0.02    # 2% network failures
  timeout_errors: 0.01    # 1% timeouts
  server_errors: 0.005    # 0.5% server errors
  
# Geographic distribution
geographic_distribution:
  north_america: 0.4
  europe: 0.3
  asia_pacific: 0.2
  other: 0.1

# Device type distribution
device_distribution:
  desktop: 0.5
  mobile: 0.35
  tablet: 0.15

# Time-based patterns
time_patterns:
  peak_hours:
    - "09:00-11:00"
    - "14:00-16:00" 
    - "19:00-21:00"
  multiplier: 1.5  # 50% more traffic during peak hours