global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ecommerce.local'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://localhost:5001/alerts'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://localhost:5001/critical-alerts'
    send_resolved: true

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://localhost:5001/warning-alerts'
    send_resolved: true
