apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m

  # Tempo for distributed tracing
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: 'elasticsearch'
        tags: ['job', 'instance', 'pod', 'namespace', 'service_name']
        mappedTags: [
          { key: 'service.name', value: 'service' },
          { key: 'service.namespace', value: 'namespace' },
          { key: 'service.instance.id', value: 'instance' }
        ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [
          { key: 'service.name', value: 'service' },
          { key: 'service.namespace', value: 'namespace' }
        ]
        queries:
          - name: 'Request Rate'
            query: 'sum(rate(http_server_requests_total{$$__tags}[5m]))'
          - name: 'Error Rate'
            query: 'sum(rate(http_server_requests_total{$$__tags,status=~"5.."}[5m])) / sum(rate(http_server_requests_total{$$__tags}[5m]))'
          - name: 'Response Time P95'
            query: 'histogram_quantile(0.95, sum(rate(http_server_requests_duration_seconds_bucket{$$__tags}[5m])) by (le))'

  # Elasticsearch for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: 'ecommerce-logs-*'
    isDefault: false
    jsonData:
      index: 'ecommerce-logs-*'
      timeField: '@timestamp'
      esVersion: '8.11.0'
      includeFrozen: false
      logMessageField: 'message'
      logLevelField: 'level'
      maxConcurrentShardRequests: 5

  # AlertManager
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    jsonData:
      implementation: prometheus

  # TestData DB for testing
  - name: TestData DB
    type: testdata
    isDefault: false